## Shared libraries
usr/lib/openmpi/lib/libmca_common_sm.so.4.0.4
usr/lib/openmpi/lib/libmpi_cxx.so.1.1.3
usr/lib/openmpi/lib/libmpi_mpifh.so.12.0.0
usr/lib/openmpi/lib/libmpi.so.12.0.2
usr/lib/openmpi/lib/libmpi_usempif08.so.11.1.0
usr/lib/openmpi/lib/libmpi_usempi_ignore_tkr.so.6.1.0
usr/lib/openmpi/lib/libompitrace.so.0.0.0
usr/lib/openmpi/lib/libopen-pal.so.13.0.2
usr/lib/openmpi/lib/libopen-rte.so.12.0.2
usr/lib/openmpi/lib/libmca_common_cuda.so.1.0.7
usr/lib/openmpi/lib/libmca_common_cuda.so.1
## Plugins
usr/lib/openmpi/lib/openmpi/*.so
## Other files
usr/lib/openmpi/lib/*.mod
